### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by raziurtotha** [denisa-ms/azure-data-and-ai-examples#1]
Hi, I have followed your code. I am getting the following error:

``
Traceback (most recent call last):
  File "/home/dfr_ai/scripts/azure_123.py", line 33, in <module>
    qa({"query": "What is this document about?"})
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 133, in _call
    answer = self.combine_documents_chain.run(
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 445, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py", line 106, in _call
    output, extra_return_dict = self.combine_docs(
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py", line 165, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 252, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 102, in generate
    return self.llm.generate_prompt(
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/llms/base.py", line 188, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/llms/base.py", line 281, in generate
    output = self._generate_helper(
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/llms/base.py", line 225, in _generate_helper
    raise e
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/llms/base.py", line 212, in _generate_helper
    self._generate(
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/llms/openai.py", line 319, in _generate
    response = completion_with_retry(self, prompt=_prompts, **params)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/llms/openai.py", line 89, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/home/dfr_ai/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/dfr_ai/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/langchain/llms/openai.py", line 87, in _completion_with_retry
    return llm.client.create(**kwargs)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/dfr_ai/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found
``

any suggestions on what might be the issue here?

**Comment by jainpradeep** [comment]
Hello. Did you fix the issue?
